### ISSUE TITLE
POS bays have no limits

### ISSUE THREAD

**Issue by jdhirst** [EvEmu-Project/evemu_Crucible#56]
From AlasiyaEvE created by [ryllae](https://github.com/ryllae): zhyrohaad/AlasiyaEvE#68  

Anchor a Control tower.  Insert 5M of 70k m^3 fuel blocks in the fuel bay. (!)  Move fuel into the strontium bay (!).

**Comment by jdhirst** [comment]
at this point, i'll have to assume pos inventory isnt being checked properly.
this will be addressed later.

**Comment by jdhirst** [comment]
this seems to be fixed

main is not updated as of yet.

**Comment by jdhirst** [comment]
all container capacity checks have been fixed.

**Comment by jdhirst** [comment]
Launching a control tower causes a crash.  I've also found several planets have "already have a tower", but don't.

**Comment by jdhirst** [comment]
this will tie in with container checks being working along with bugs #57, #58, and #37 
all these bugs are symptoms of same method error.
and surprise, surprise, it's a coding error!!

**Comment by zhyrohaad** [comment]
this is still present on my latest testing (for pos launch/anchor errors)
seems tower inv checks arent working.
