### ISSUE TITLE
Character re-customization can be completed now, but the data is not persisted

### ISSUE THREAD

**Issue by jdhirst** [EvEmu-Project/evemu_Crucible#76]
From AlasiyaEvE created by [ryllae](https://github.com/ryllae): zhyrohaad/AlasiyaEvE#7  

**Describe the bug**
Re-customization hangs entering Portrait mode

**To Reproduce**
Dock, Click Re-customization, click Next to go to Portrait mode.

**Comment by jdhirst** [comment]
Taking new pictures now works!

However, if you customize your character (say, change your hair color), take a new picture, then re-enter customization, you revert back to the original.  This happens even if you logout in between.  It looks like customizations aren't being persisted.

**Comment by jdhirst** [comment]
Ok, the data saves, but now I get a really strange behavior:  After customizing my toon, I can see the new image in the toon selection screen, but if I click customize, I get my *original* choices.

**Comment by jdhirst** [comment]
i didnt update when fix was pushed to main.
pls test again to verify

**Comment by jdhirst** [comment]
ahhh.....yeah, i forgot to save new data after recustomization is complete.
i'll add it and post when its updated

**Comment by jdhirst** [comment]
turns out this uses an unimplemented data set.
this particular data wasnt understood and no one knew what it was for.
i see it now, and will work on implementing it.
may take a while.

**Comment by jdhirst** [comment]
oh neat.
never tried any of that before.....mostly because i've never seen it.
ill revisit this when the load lessens a bit
.....or pencil it into my copious free time!  lol

**Comment by jdhirst** [comment]
Can you check this with logserver running while using the launcher?  Post relevant log sections, not the whole thing there's some sensitive stuff in them occasionally.

**Comment by jdhirst** [comment]
i have found and implemented this data set.
it will require a db wipe to fully implement, which will be done at a later date.
i will post back on here when this fix is pushed to main server

**Comment by jdhirst** [comment]
oh.  didnt know that was an option, so it was never tested.
will have to look into that one.

**Comment by jdhirst** [comment]
Correction: after logging back in today, I'm back to my previous picture.  So either last attempt at character customization either didn't work, reverted, or something else is still wrong.  And I still can't save with my "illegal" outfit.

**Comment by jdhirst** [comment]
this fix has been pushed to main server.
please test again to verify the fix

**Comment by jdhirst** [comment]
i'll look at this more later.
its a bit low on the list now.

**Comment by jdhirst** [comment]
Also, my toon is currently wearing "unavailable" clothes, but attempting to save with those on generates a `ItemNotAtStation` error message in the final save step (after the "uploading your portrait to evemu) - yet I'm still offered the ability to select those items in the clothing panel.  Should probably be consistent there that I can't select something that's going to be invalid.

And while disabling the usually-unavailable clothing might technically be a "fix", I wouldn't mind that going unfixed, just because I like abusing it.  Or make it admin-only.

Also curious, I get the "proper" name of the item in the error message, but the editor doesn't show that.

![Annotation 2019-12-02 222047](https://user-images.githubusercontent.com/51723245/70020371-0beffc00-1552-11ea-8954-10744774eda2.png)

![Annotation 2019-12-02 222052](https://user-images.githubusercontent.com/51723245/70020375-0f838300-1552-11ea-8b81-61cfc85d1f38.png)

**Comment by zhyrohaad** [comment]
@zhyrohaad 
this convo is out of order.
latest update from original post stated this is still broken, and i dont know why.
we may have to limit "special" outfits until we have a better understanding of how they are defined and fit into character data.
